### ISSUE TITLE
[Feature request] Add the hability of upload via TCP/IP (in Wiznet W5100-based boards)

### ISSUE THREAD

**Issue by q2dg** [Optiboot/optiboot#122]
I've read this and it seems wonderful: http://sowerbutts.com/optiboot-w5100/

**Comment by WestfW** [comment]
It sounds good, but it's based on a very old version of Optiboot, and would significantly complicate and clutter the source code to add it. (also, it wasn't written to have the tcp code be easily excludable.)
So I don't think I will be adding this to the main optiboot repository.
However, I've created a wiki page where I'll link "interesting" optiboot-derived versions: <https://github.com/Optiboot/optiboot/wiki/OtherVersions>

**Comment by q2dg** [comment]
Oh, it seems very reasonable. Thanks!!!
