### ISSUE TITLE
Is there no optiboot board for the arduinio uno ?

### ISSUE THREAD

**Issue by dakky** [Optiboot/optiboot#126]
I want do use optiboot for my arduino uno. I managed to place the files at the correct location, At least, i can see some new optiboot boards (the documentation needs some finetuning imho :D )

But there is no arduinio uno optiboot board available?

![image](https://cloud.githubusercontent.com/assets/579584/7337808/81b53fd4-ec37-11e4-8518-4bd41f4e6342.png)

how to burn optioboot to an arduino uno?

**Comment by WestfW** [comment]
Uno uses optiboot by default; no new boards.txt entry is needed.
