### ISSUE TITLE
ATtiny84 compile broken in older avr-gcc versions

### ISSUE THREAD

**Issue by WestfW** [Optiboot/optiboot#134]
The changes that fixed VIRTUAL_BOOT_PARTITION (https://github.com/Optiboot/optiboot/issues/120 ) break the ATtiny84 compile with older versions of avr-gcc, because the include files do not define WDT_vect_num

(Doesn't work w 4.3.2, does work with 4.8.1  I haven't narrowed it down further.)

**Comment by WestfW** [comment]
(It's not that there ISN'T a WDT vector; the ioxxx.h file just fails to define the _vect_num symbols.  Grr.)

**Comment by majekw** [comment]
If #135 will be accepted, it could be fixed by adding '-Dsave_vect_num=4' in Makefile.
