### ISSUE TITLE
Clean up boot.h stuff

### ISSUE THREAD

**Issue by majekw** [Optiboot/optiboot#148]
Optiboot ships with it's own modified copy of `<avr/boot.h>`.
In fact, changes are:
- new defines with short versions  of `spm` calls (using `out` instead of `sts`)
- modification of `boot_` higher level macros to use short versions

How it's used:
- directly by calling new macros using `__boot_*_short`
- calling hacked `boot_rww_enable`

What can be done:
- include standard `<avr/boot.h>` to get all bits names and abstract SPM(C)SR
- include optiboot's boot.h stipped down only to new `__*_short` macro versions
- change `boot_rww_enable` to `__boot_rww_enable_short` for consistency with other direct calls

Pros:
- less code to maintain
- consistency
- free updates for new chips from newer versions of avr-gcc
- it could be easier and less 'hacky' to add support for other chips (for example Atmega128) by abstracting `__boot_*` calls by for example `optiboot_*` conditional macros defined in stripped down local boot.h

**Comment by WestfW** [comment]
2c2a4d24c3fa19b013e2685463ce9edcd44e5177
