### ISSUE TITLE
Signature undeclare if make atmega324p/atmega164p

### ISSUE THREAD

**Issue by gitronik** [Optiboot/optiboot#155]
this is from cmd....

help please....

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\Arduino\arduino-1.0.6\hardware\arduino\bootloaders\optiboot>omake atmega324p

D:\Arduino\arduino-1.0.6\hardware\arduino\bootloaders\optiboot>..\..\..\tools\av
r\utils\bin\make OS=windows ENV=arduino atmega324p
BAUD RATE CHECK: Desired: 115200, Real: 113636, UBRRL = 21, Error=1.3%
../../../tools/avr/bin/avr-gcc -g -Wall -Os -fno-inline-small-functions -fno-spl
it-wide-types -mshort-calls -mmcu=atmega324p -DF_CPU=20000000L  -DBAUD_RATE=1152
00 -DLED_START_FLASHES=3         -c -o optiboot.o optiboot.c
optiboot.c: In function 'main':
optiboot.c:629: error: 'SIGNATURE_0' undeclared (first use in this function)
optiboot.c:629: error: (Each undeclared identifier is reported only once
optiboot.c:629: error: for each function it appears in.)
optiboot.c:630: error: 'SIGNATURE_1' undeclared (first use in this function)
make: *** [optiboot.o] Error 1

**Comment by WestfW** [comment]
I don't see any signs that the current optiboot supports 324p at all; what source code are you using?
iom324*.h all contain definitions for SIGNATURE_0 and etc, so it seems like pretty fundamental source error?
