### ISSUE TITLE
Newer gcc creates unnecessary stack frame.

### ISSUE THREAD

**Issue by WestfW** [Optiboot/optiboot#160]
Streef noticed that with newer versions of gcc, main() is setting up a stack frame.
He needed this fixed for a reset-flags change (https://github.com/Optiboot/optiboot/pull/125 ), but I'd like it gone separately...

**Comment by WestfW** [comment]
FWIW, this is gone in the even newer (Atmel-released) toolchain:
avr-gcc (AVR_8_bit_GNU_Toolchain_3.6.0_487) 5.4.0

**Comment by majekw** [comment]
It's known bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50925
Workaround for older avr-gcc: 
https://github.com/majekw/optiboot/commit/6262a28c994034c9303185ce7d46a31ded0c8a00

**Comment by WestfW** [comment]
I'll close this since it turns out to have been a (now fixed) gcc bug.
