### ISSUE TITLE
"Release" Atmel Studio targets incorrect...

### ISSUE THREAD

**Issue by WestfW** [Optiboot/optiboot#165]
Apparently, the "release" targets of the Atmel Studio projects (https://github.com/Optiboot/optiboot/issues/150 ) are not correct (I only ever built "debug" targets.)

**Comment by aethaniel** [comment]
I can confirm the "debug" works very well at the moment :wink:

**Comment by syddo** [comment]
@aethaniel I can't compile in AS7... have you tried?

**Comment by aethaniel** [comment]
I always used existing makefile with avr-gcc from studio in the path. Worked perfectly every time.

On 15 March 2017 09:53:08 CET, Syd Pao <notifications@github.com> wrote:
>@aethaniel I can't compile in AS7... have you tried?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Optiboot/optiboot/issues/165#issuecomment-286678073

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by WestfW** [comment]
>> can't compile in AS7
Sheesh.   Do you get past the "upgrade" to the new AS infrastructure?  I can't even get the project to load under the latest AS7.   Grr.

**Comment by aethaniel** [comment]
Oooops, i didn't see the history of the thread last time. Sorry.
I will take look during the week end to see if i can bring any help.

**Comment by WestfW** [comment]
Is this https://github.com/Optiboot/optiboot/issues/200 ?
(which should be fixed now.)

**Comment by WestfW** [comment]
https://github.com/Optiboot/optiboot/commit/70bd967c3cc5e242f09cb4849e2ce396bfc60fe7
