### ISSUE TITLE
Strange line in boards.txt file

### ISSUE THREAD

**Issue by fra87** [Optiboot/optiboot#169]
Hello
in the boards.txt file (for arduino 1.6.4, so in the repository it is called boards-1.6.txt) at line 110 there is this line

optiboot28.menu.cpu.8MHz.bootloader.low_fuses=0xE2

Now, since there is no menu for CPU - 8MHz and the previous line is
optiboot28.menu.cpu.atmega8.bootloader.low_fuses=0xBF
I think that the line 110 should be commented out or removed, or at least there is something strange with that

**Comment by WestfW** [comment]
Fixed in commit https://github.com/Optiboot/optiboot/commit/be06597525886d9e6c36a0496f570d427b667e05
