### ISSUE TITLE
Arduino IDE 1.6.11 doesn't link in code for ".init0" section (resetFlags).

### ISSUE THREAD

**Issue by gitmeister** [Optiboot/optiboot#187]
Noticed my watchdog code was always failing to provide the reset cause and noticed that "resetFlags" was never getting updated.

Dumped the "map" file with avr-objdump -trhd FIO-WDT.ino.elf > map.txt, and noticed that the ".init0" as well as the function resetFlagsInit() never appear anywhere. This is using the stock "test_reset.ino".

As a test I threw in a call to resetFlagsInit() in the code just to see if it would magically appear in the map file, and it did. Is the optimizer messing up thinking it doesn't have to generate code for ".init0" sections?

EDIT1: Added the following line in the code "if (resetFlags==0xEE) resetFlagsInit();" which will never run but will force the code for resetFlagsInit() to be generated and then ran "test_reset.ino", now it works with "Have reset flag value 0x8 Watchdog."

EDIT2: Removed -Os (full optimization) during the compilation (in platform.txt), and removed the dummy line in EDIT1, and the code works as intended. I tried -O1 and -O2 for fun but it fails with odd values for resetFlags.

EDIT3: As a test, added a recent addition to the --attribute-- option to selectively disable optimization: --attribute-- ((optimize("O0")))
Added this to the definition of resetFlagsInit() function definition. No joy. Note that 2x(underscore) is a markup code here so fix the --.

**Comment by gitmeister** [comment]
Thanks to facchinm from the Arduino project for proposing this fix/workaround: Add `__attribute__ ((used))` to the prototype for resetFlagsInit().

This seems to apply to newer Arduino IDEs (i'm using 1.6.11) that use the new compiler optimizer switch -flto.

**Comment by ctag** [comment]
I ran into this problem this week as well. Thank you for bringing the solution back from the other thread.
