### ISSUE TITLE
Compatability with GSM/GPRS

### ISSUE THREAD

**Issue by gorlapraveen** [Optiboot/optiboot#189]
Can we use optiboot bootloader for upgrading the frimware over GSM/GPRS ,where the frimware would be available on the server and GSM/GPRS can download it.

**Comment by WestfW** [comment]
Traditionally, the problem with uploading over wireless communications is that they do not provide a mechanism for dropping the DTR signal and causing an auto-reset.  Optiboot can be used without that, but it tends to be pretty awkward - it involves hitting the reset button manually at just the right time (which is exactly what a wireless user doesn't want to have to do!)
