### ISSUE TITLE
Defining AVR_FREQ causes make to fail

### ISSUE THREAD

**Issue by ajfre** [Optiboot/optiboot#194]
Running 'make atmega328 AVR_FREQ=10000000L' (on Linux mint 17) causes make to fail with
> baudcheck.tmp.sh: line 17: ( ($ + 115200 * 4) / ((115200 * 8))) - 1 : syntax error: operand expected (error token is "$ + 115200 * 4) / ((115200 * 8))) - 1 ")
as first diagnostic. (The value of AVR_FREQ doesn't matter.)

**Comment by WestfW** [comment]
I believe you're running into the Make bug described in https://github.com/Optiboot/optiboot/issues/106
