### ISSUE TITLE
Load over I2C (instead of UART)

### ISSUE THREAD

**Issue by deoqc** [Optiboot/optiboot#198]
I have several Arduinos connected by I2C with a Raspberry Pi. I would like to program them over I2C. 

Is it reasonable to do it (using a modified Optiboot loader)? If so, what would be the path?

---

*ps: This may very well be classified as 'out-of-scope', but I'm searching for enlightenment on this issue.*

**Comment by njh** [comment]
I can't see any reference to i2c or TWI in the codebase.
I suspect that this would be a completely different bootloader codebase.

I have a similar interest but with the bootloader as the i2c master - loading the firmware from an external EEPROM.

**Comment by WestfW** [comment]
Most of optiboot is dealing with the serial communications protocol.  Replacing that with I2C would essentially be a completely different bootloader.
