### ISSUE TITLE
How can I verify if my arduino is bootloaded?

### ISSUE THREAD

**Issue by Porama6400** [Optiboot/optiboot#207]
How can I verify if my arduino is bootloaded with Optiboot?

**Comment by WestfW** [comment]
If an Arduino is bootloaded (in general) it will blink the "pin 13 led" three times after a hardware reset.   However, this is true of the prior bootloaders as well, so it doesn't prove that optiboot is present.

Optiboot normally runs at 115200bps, while the older bootloaders ran slower.  A command like:
**avrdude -v -patmega328 -carduino -P COM4  -b115200**
should get a response from an arduino with Optiboot loaded.  Somewhere in the output should be a line showing the firmware version:
        **Firmware Version: 4.4** 
 Stock Arduino Uno (and the .hex/source included with the Arduino IDE) will return "4.4", and any built from this source repository will be higher than that.
