### ISSUE TITLE
Address out of range error when using <avr/signature.h>

### ISSUE THREAD

**Issue by IMAN4K** [Optiboot/optiboot#224]
Here is the complete log:
```
avrdude: ERROR: address 0x840003 out of range at line 618 of C:\Users\<user>\AppData\Local\Temp\arduino_build_890984/<sketch>.ino.hex
avrdude: read from file 'C:\Users\<user>\AppData\Local\Temp\arduino_build_890984/<sketch>.ino.hex' failed
the selected serial port avrdude: read from file 'C:\Users\<user>\AppData\Local\Temp\arduino_build_890984/<sketch>.ino.hex' failed
 does not exist or your board is not connected
```
When removing `#include <avr/signature.h>` from sketch, everything get back to life! (because this header will add extra info to final bin)

**Comment by WestfW** [comment]
1) I'm not sure what you expect including .signature to do; the documentation says it includes the signature in a special section (.signature) in the .elf file, for use by programming software.  But the Arduino IDE doesn't use the .elf file, and doesn't use appropriate objcopy arguments to omit the section when creating the .hex file, which is what is causing this error.

2) this has nothing to do with optiboot.
