### ISSUE TITLE
current selected board needs core arduino:arduino

### ISSUE THREAD

**Issue by kurtjcu** [Optiboot/optiboot#225]
Hello,
I have just installed optiboot by unzipping in hardware folder.
Boards list is populated however each of the optiboot boards has the error message when selected.
"The current selected board needs the core 'arduino:arduino' that is not installed."

All optiboot boards have this error.

**Comment by WestfW** [comment]
"unzipping in hardware folder" is not a valid installation technique in any "recent" version of the Arduino IDE.  Please follow the instructions on using the "board manager" in the README file.
(If you're running some older version of the IDE, at least tell us which ones.)

I've confirmed that things compile correctly when using the .json-based install with Arduino IDE 1.8.5
