### ISSUE TITLE
Possible to Burn Optiboot via USB?

### ISSUE THREAD

**Issue by johnyradio** [Optiboot/optiboot#228]
hi, can Optiboot be burned to an ATTiny85 dev board using the USB connector?

https://www.ebay.com/itm/292359646596

thx

**Comment by WestfW** [comment]
No; those USB-connected tin85 boards use a special bootloader to enable usb connectivity.  Even if you could put Optiboot on it, you would only be able to upload over a serial connection (requiring an extra USB/Serial converter) thereafter.
