### ISSUE TITLE
128 word Optiboot for ATmega88/168 (assembler rewrite)

### ISSUE THREAD

**Issue by bitflipser** [Optiboot/optiboot#230]
https://github.com/bitflipser/miniOptiboot

**Comment by davidbitton** [comment]
@WestfW I just tried and put ASMboot on my 328p board. I used the following:
```
avrdude -v -v -c usbasp -p m328p -Uflash:w:ASMboot_328_16.hex:i
```

but using the Arduino IDE to push a sketch via FTDI fails with the `avrdude: stk500_getsync()` error. Ideas?
