### ISSUE TITLE
Add 1.0MHz Internal Oscillator in Attiny13A

### ISSUE THREAD

**Issue by mchiappinam** [Optiboot/optiboot#232]
Hello,

Please add 1.0MHz Internal Oscillator in Attiny13A.

Thanks.

**Comment by WestfW** [comment]
Optiboot does not support the tiny13a.  (if it did, it would take up half the memory!)
It also doesn't have a 1MHz Internal Oscillator.  (It has 4.8MHz and 9.6MHz depending on fuse settings, which is probably what you're talking about.  With possible divide-by-8 prescaler.)
