### ISSUE TITLE
New version of Hex file 7.0

### ISSUE THREAD

**Issue by salinm1** [Optiboot/optiboot#240]
Hi,

you prepared new version fo optiboot.c ver 7.0, can you prepare please also optiboot_atmega328.hex in ver 7.0? I have big problem with implemention of this bootloader to arduino nano and I fink that this new version help.  

Thank you

**Comment by WestfW** [comment]
https://github.com/Optiboot/optiboot/commit/9b83da348910ec26de5ce77416e7a9b2c3c0bfb8

**Comment by WestfW** [comment]
Eventually, there will be a "release."
Meanwhile, the popular .hex files have been committed.
