### ISSUE TITLE
atmega 2560 hex files missing

### ISSUE THREAD

**Issue by HKEB** [Optiboot/optiboot#261]
I wanted to update Optiboot an the Arduino Mega Compatible Board.

It seems the "optiboot_atmega2560.hex" File is missing in the zip Files. 
Also the Boad Manager installs it but there is no .hex Files installed

Since I'm too much of a beginner to compile them myself I just wanted to ask for them.

**Comment by WestfW** [comment]
As the number of chips and options increases, I'm trying to get this ("core") Optiboot repository out of the business of providing .hex files.  There are people providing more complete Arduino-compatible "board" definitions that are fulfilling the need for pre-built hex files for the common (and not-so-common) configurations, and you should probably use one of those.

MCUDude's MegaCore has 2560 .hex files: https://github.com/MCUdude/MegaCore/tree/master/avr/bootloaders/optiboot_flash/atmega2560
And he has newer code in his optiboot-flash repository.  You'd probably want this one:
https://github.com/MCUdude/optiboot_flash/blob/master/bootloaders/atmega2560/16000000L/optiboot_flash_atmega2560_UART0_115200_16000000L_eeprom_support.hex
