### ISSUE TITLE
BIGBOOT's stored build information is in the wrong place!

### ISSUE THREAD

**Issue by WestfW** [Optiboot/optiboot#267]
https://github.com/Optiboot/optiboot/pull/266

I found when compiling with BIGBOOT that __do_copy_data was being placed before the jump table, due to the human-readable config flag info being placed in .data. Using the .progmem section puts them before most of .text still, and using .text.buildinfo to sort into the .text.* rule produced linker errors (optiboot.c:(.init9+0x10a):  warning: internal error: out of range error optiboot.c:(.init9+0x168):  warning: internal error: out of range error, on the lines using eeprom_*_byte()). I placed them in .fini8 to get it ordered properly to work, but someone with more linker-fu might have a better solution.

**Comment by justarandomgeek** [comment]
Upon further thought, possibly a better fix is to move the jump table itself from `.init8` to `.vectors`, which looks like it should sort before pretty much everything according to the mapfile output!
