### ISSUE TITLE
Comment in boards-1.6.txt about Pro Micro probably was intended to be Pro Mini

### ISSUE THREAD

**Issue by dmjlambert** [Optiboot/optiboot#274]
I noticed in the 8.0 release zip boards.txt and in boards-1.6.txt there is this comment:
## Optiboot on 32pin (SMT) CPUs (Nano, Pro Micro, etc.)
I think perhaps that was meant to say Pro Mini instead of Pro Micro.

**Comment by WestfW** [comment]
https://github.com/Optiboot/optiboot/commit/ca5ef0a5c94072ccd283900b5e78204cc186676c
