### ISSUE TITLE
The jump destination of the patched reset vector is off one word.

### ISSUE THREAD

**Issue by ngkz** [Optiboot/optiboot#275]
`RJMP k` means jump to `PC + 1 + k`, not `PC + k`.
You forgot to subtract one from operand when patching reset vector. Because of this, the first instruction of main() won't execute when flash size is <8K and using virtual boot partition.

**Comment by WestfW** [comment]
Huh.   You mean main() of optiboot itself, right?

**Comment by ngkz** [comment]
>Huh. You mean main() of optiboot itself, right?
Yes

**Comment by ngkz** [comment]
I confirmed that the bug fixed. (Tested with ATTiny85)
```
       0:       df ce           rjmp    .-578           ;  0x1dc0
```
```
    1dc0:       01 c0           rjmp    .+2             ;  0x1dc4
    1dc2:       0d c1           rjmp    .+538           ;  0x1fde
    1dc4:       11 24           eor     r1, r1
```
