### ISSUE TITLE
how to make atmega1284p.hex file ?

### ISSUE THREAD

**Issue by SpasNH** [Optiboot/optiboot#279]
Hi. Can anyone tell me what command I have to put in the terminal to make the  bootloader for ATmega1284p ? It's missing in the bootloaders directory and I don't understand the instructions in the readme.txt file. Thanks

**Comment by WestfW** [comment]
`make atmega1284p LED_PIN=B7     `
Or something like that.  (assuming you have tools installed.)

Or grab one of the pre-built versions from MCUdude's MightyCore: https://github.com/MCUdude/MightyCore/tree/master/avr/bootloaders/optiboot_flash/bootloaders/atmega1284p

**Comment by SpasNH** [comment]
thank you.
