### ISSUE TITLE
ATmega2560 without Arduino

### ISSUE THREAD

**Issue by Cfritsch** [Optiboot/optiboot#280]
Hi! I am looking for an optiboot hex-file for the ATmega2560. I don't want to make use of the Arduino environment or any extra cores. I really just need the actual Bootloader. Does something like that exist?

Thank you!

**Comment by WestfW** [comment]
I've deprecated the inclusion of .hex files in the Optiboot repository.  With the added chips and options, there are just too many combinations.  You're best off compiling from the Source Code.
If you don't want to build from source code, you can use one of the .hex files maintained by MCUDude for his Arduino MegaCore:
https://github.com/MCUdude/MegaCore/tree/master/avr/bootloaders/optiboot_flash/bootloaders/atmega2560

(The standard "16MHz, UART0, 115200bps, LED Blink on PB7" Bootloader is:
https://github.com/MCUdude/MegaCore/blob/master/avr/bootloaders/optiboot_flash/bootloaders/atmega2560/16000000L/optiboot_flash_atmega2560_UART0_115200_16000000L_B7_BIGBOOT.hex
The naming scheme is regular; once you find the one you want, right click on "raw" and save it to a .hex file, which can be done separately from the "full" MegaCore install.)
