### ISSUE TITLE
TIMEOUT_MS are described but not used

### ISSUE THREAD

**Issue by N-Storm** [Optiboot/optiboot#284]
The TIMEOUT_MS macro are describe in optiboot.c, optiboot_x.c headers but not used. This leads to disambiguation. PR #268 already has the proposed solution for this issue.

**Comment by WestfW** [comment]
Feature added and comment fixed in https://github.com/Optiboot/optiboot/commit/0b9a50d4e6e6f88d7676573a88329f3c4d2ec54e
The option is in seconds, which makes more sense. (and is compatible with optiboot_x for mega0)
