### ISSUE TITLE
Error loading sketch

### ISSUE THREAD

**Issue by AB-informatica-service** [Optiboot/optiboot#289]
I burned Optiboot on Atmega328P standalone on breadboard with the help of a 16KHz oscillator and I did it.

Now I cannot load the sketches, I am using the Windows Store version 1.8.39.0
I have selected the "Optiboot on 28-pin cpus" card with "ATmega328P" processor with "1MHz (int)" CPU Speed and I have set the programmer to "AVRISP mkII".

And it gives me this error:
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x75
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x75

As SPI interface I am using arduino without processor with RX and TX pin.
Where am I wrong?

**Comment by WestfW** [comment]
Please start a discussion in the bootloader section of the Arduino Forums, including the output when you enabled "verbose" output for upload in the IDE "Preferences" panel.
I'm willing to tolerate a certain amount of "discussion" in the "issues" here, but it's not a general purpose help area.
