### ISSUE TITLE
Where can I find the Hex file for ATmega168A/PA?

### ISSUE THREAD

**Issue by ArminJo** [Optiboot/optiboot#304]
There are a lot of China clones putting an ATmega 168 instead an ATmega 328 on a Nano board. It would be desirable to have Optiboot available as precompiled hex file for these boards.

**Comment by WestfW** [comment]
This is available as part of MCUDude's MiniCore ( https://github.com/MCUdude/MiniCore )
Thus the recommendation in the Readme file:

> Most end users should find a supported "Arduino Core" that includes Optiboot for their desired target, and install that.

**Comment by ArminJo** [comment]
Thanks!
