### ISSUE TITLE
Reassign RX TX pins 

### ISSUE THREAD

**Issue by Kabron287** [Optiboot/optiboot#307]
Hi there,
I work with Attiny85 and I need to use other than PB0, PB1 softuart pins.
What command option should I use?
Thanks in advance,
Vladimir

**Comment by WestfW** [comment]
Currently, edit pin_defs.h - find the occurrence of ATtiny85, which will look like:
```
/*------------------------------------------------------------------------ */
#if defined(__AVR_ATtiny85__)
/*------------------------------------------------------------------------ */
/* LED is on B2 */
#if !defined(LED)
#define LED   B2
#endif

#if SOFT_UART
#define UART_PORT   PORTB
#define UART_PIN    PINB
#define UART_DDR    DDRB
#define UART_TX_BIT 0
#define UART_RX_BIT 1
#endif
#endif
```
Change UART_TX_BIT and UART_RX_BIT to whatever you want.  (tiny85 only has PORTB, right?)

It'd be an interesting modification, to allow selecting the pins from the "make" command, but it would be a bit of work.
