### ISSUE TITLE
PC Tool to communicate with optiboot to flash the Application 

### ISSUE THREAD

**Issue by BeminGhobreal** [Optiboot/optiboot#319]
HI all, I'm working on a  custom PC tool to upload the flash. I'm using the atmega328pb and the optiboot bootloader, I'm trying to use the stk500 command but the bootloader not responding. The issue is in the my pc application because the bootloader working with averdude.
I couldn't find any documentation or command protocol regarding communicating with optiboot from the PC  ?
Any suggestions ?

**Comment by WestfW** [comment]
Is your PC-side code using STK500v1 or STK500v2?  They're substantially different.
See https://github.com/Optiboot/optiboot/wiki/HowOptibootWorks

**Comment by BeminGhobreal** [comment]
Using STKV500v1

**Comment by BeminGhobreal** [comment]
I can't find anything has to do with the crc ? how is the crc calculated

**Comment by BeminGhobreal** [comment]
How to program flash memory using optiboot ?

**Comment by WestfW** [comment]
There is no actual CRC.  the "20" is more of a "check character", despite the symbol name.

What part of the previous references are you stuck on?  In between the wiki page and the Atmel App note, it should be pretty clear, and I don't know of anything else.

**Comment by BeminGhobreal** [comment]
I resolved all the above, but now My issue is when I program the flash memory I don't get the /14/10 return , which I'M SUPPOSE TO GET ?
