### ISSUE TITLE
Microchip Studio and Atmega328pb

### ISSUE THREAD

**Issue by SandeepKel** [Optiboot/optiboot#338]
Trying to build the project for Atmega328pb with custom bootloader.

The build works correctly with built-in makefile, the moment i redirect to custom  make file, it fails to build attached error and make file for your reference
![build_error](https://user-images.githubusercontent.com/31265247/154234617-148a4b91-36ad-442f-a18e-4328fe3d677f.png)
[Makefile.txt](https://github.com/Optiboot/optiboot/files/8078494/Makefile.txt)
.

**Comment by WestfW** [comment]
I think you want CFLAGS added to your link command as well; it might need stuff that is part of the "pack."  (although normally the bootloader build goes to avoid linking in the standard startup code via -nostartfiles, so this might not be your only problem.)

**Comment by SandeepKel** [comment]
Hey WestFW, thank you for your comments, the build is successful after adding the CFLAGS while linking.
