### ISSUE TITLE
mega2560

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Optiboot/optiboot#50]
```
is there it possible to use optiboot on the arduino mega 2560? 
Flashing for an mega2560 failed for me;the 1280 version is probably 1280 only...
greetings,
 bernhard
```

Original issue reported on code.google.com by `bernhard...@gmail.com` on 8 Dec 2011 at 12:00

**Comment by majekw** [comment]
It looks like flashing more than 128KB is possible using STK500v1 protocol. It's supported in Avrdude 6.1, so Optiboot's side added in #159
