### ISSUE TITLE
The last N bytes of an upload cannot be 0xFF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Optiboot/optiboot#59]
```
What steps will reproduce the problem?
1. Run the attached sketch.

What is the expected output? What do you see instead?
The LED should not turn on, but it does.

What version of the product are you using? On what operating system?
Arduino 0022 or 1.0, WinXP or Win7, Arduino Uno SMD edition or breadboarded 
ATmega328P, Optiboot loader from Arduino 1.0.

Please provide any additional information below.
Issue is evidently a combination of how AVRDUDE and optiboot work together. 
More detail is available on the Arduino forum:
http://arduino.cc/forum/index.php/topic,84243.0.html
```

Original issue reported on code.google.com by `xyzz...@gmail.com` on 10 Feb 2012 at 1:58

Attachments:
- [uploadIssue.pde](https://storage.googleapis.com/google-code-attachments/optiboot/issue-59/comment-0/uploadIssue.pde)

**Comment by WestfW** [comment]
I've confirmed that this is fixed in more recent versions of avrdude, and created a .hex file in .../examples/hex-with-FFs.hex for testing.
https://github.com/Optiboot/optiboot/commit/8fdda0b25611493fc071d8078e1d13f2afdd9bf5
