### ISSUE TITLE
Support application section writing to flash, on big parts?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Optiboot/optiboot#99]
```
One of the useful things that could be done in a "bigboot" version of optiboot 
is to provide known entry points for writing data to flash, so that the 
application section could call the bootloader to do this.  (Dangerous, though!)

```

Original issue reported on code.google.com by `wes...@gmail.com` on 12 Mar 2014 at 4:42

**Comment by majekw** [comment]
The code is here: https://github.com/majekw/optiboot/tree/entrytospm
I need to test it and write example before pull request.
Comments and testers are welcome.
Currently it fits in normal bootloader (only 6 more bytes), so 'bigboot' is not necessary :-)

**Comment by majekw** [comment]
New code available in my fork/branch - with working example!
It adds 6 bytes to overall bootloader size (464B -> 470B on Atmega328)

Tested so far on Atmega328 (Arduino Pro Mini) - it works :-)

**Comment by WestfW** [comment]
https://github.com/Optiboot/optiboot/commit/e9af37fef0cf72981b61645cd21c025bc86c9cbe
